name: SpawnerDistanceRestricter
main: com.cyprias.spawnerdistancerestricter.SpawnerDistanceRestricter
version: 0.1.0

permissions:
    spawnerdistancerestricter.exempt:
        default: false
        description: Excempt a player from distance restrictions.